app_key: "sigivvci96scd1m"
app_secret: "3sjdxyyscvdgyw6"
access_token: "d1lah8pi7h3ofw1l"
access_token_secret: '7jlnwfgejyz5agy'
user_id: '289067842'
access_type: 'app_folder'

##{"access_token": "Ksc-f3qF-KEAAAAAAAAABtxuPiXHAYyGawbYLctP35p0ntuQNpRmGTo35jnohL0s", "token_type": "bearer", "uid": "289067842"}